server:
  port: 5004
  contextPath: ""
  host: 0.0.0.0

postgres:
  host: localhost
  port: 5432
  user: admin
  password: admin123
  dbname: basyxTestDB
  maxOpenConnections: 500
  maxIdleConnections: 500
  connMaxLifetimeMinutes: 5

oidc:
  issuer: "http://localhost:8080/realms/basyx"
  audience: "discovery-service"
  jwksURL: "" 

abac:
  enabled: false
  clientRolesAudience: "discovery-service"
  modelPath: "config/access_rules/access-rules.json"