server:
  port: 5004
  contextPath: ""
  host: 0.0.0.0
  strictVerification: false

postgres:
  host: db
  port: 5432
  user: admin
  password: admin123
  dbname: basyxTestDB
  maxOpenConnections: 500
  maxIdleConnections: 500
  connMaxLifetimeMinutes: 5

oidc:
  trustlistPath: "/config/trustlist.json"

abac:
  enabled: true
  enableDebugErrorResponses: true
  modelPath: "/config/access_rules/access-rules.json"

general:
  enableImplicitCasts: false
  enableDescriptorDebug: true
  discoveryIntegration: true
