
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxTestDB
    volumes:
      - ../../../basyxschema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxTestDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  aas-repository:
    build:
      context: ../../..
      dockerfile: ./cmd/aasrepositoryservice/Dockerfile
    environment:
      SERVER_PORT: 5105
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DBNAME: basyxTestDB
      POSTGRES_MAXOPENCONNECTIONS: 50
      POSTGRES_MAXIDLECONNECTIONS: 10
      POSTGRES_CONNMAXLIFETIMEMINUTES: 5
      ABAC_ENABLED: "false"
    ports:
      - "5105:5105"
    depends_on:
      - db
    restart: unless-stopped


