server:
  port: 5004
  contextPath: ""
  host: 0.0.0.0

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: snoopy2002
  # dbname: basyxGoBenchmarkTest
  dbname: basyx
  maxOpenConnections: 500
  maxIdleConnections: 500
  connMaxLifetimeMinutes: 5

jws:
  privateKeyPath: "./rsa-key.pem"
