server:
  port: 5004
  contextPath: ""
  host: 0.0.0.0

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: snoopy2002
  # dbname: basyxGoBenchmarkTest
  dbname: basyxCoreWorks
  maxOpenConnections: 500
  maxIdleConnections: 500
  connMaxLifetimeMinutes: 5

oidc:
  trustlistPath: "config/trustlist.json"


abac:
  enabled: false
  enableDebugErrorResponses: true
  modelPath: "config/access_rules/access-rules.json"
