server:
  port: 5004
  contextPath: ""
  host: 0.0.0.0

postgres:
  host: localhost
  port: 5432
  user: admin
  password: admin123
  dbname: basyxTestDB
  maxOpenConnections: 500
  maxIdleConnections: 500
  connMaxLifetimeMinutes: 5

oidc:
  issuer: "https://iam-security-training.com/consumer/sts"
  audience: "https://credential.aas-voyager.com/resources"

abac:
  enabled: true
  enableDebugErrorResponses: true
  clientRolesAudience: "https://iam-security-training.com/consumer/sts"
  modelPath: "config/access_rules/access-rules.json"