services:

  # Apache reverse proxy to support DNS lookup
  apache-proxy:
    image: httpd:2.4-alpine
    container_name: apache-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
    depends_on:
      - keycloak
    networks:
      - basyx-java-server-sdk

  aas-registry:
    container_name: aas-registry
    image: eclipsebasyx/aasregistry-go:SNAPSHOT
    ports:
      - 8082:8080
    environment:
      - VIRTUAL_HOST=aasreg.basyx.localhost
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - VIRTUAL_PORT=8080
      - SERVER_PORT=8080
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=true
      - ABAC_MODELPATH=/security_env/access-rules.json
      - OIDC_TRUSTLISTPATH=/security_env/trustlist.json
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--output-document=-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
      keycloak-healthcheck:
        condition: service_completed_successfully
    volumes:
      - ./security_env:/security_env
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    networks:
      - basyx-java-server-sdk

  sm-registry:
    container_name: sm-registry
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - 8083:8080
    environment:
      - VIRTUAL_HOST=smreg.basyx.localhost
      - VIRTUAL_PORT=8080
      - BASYX_CORS_ALLOWED_ORIGINS=*
      - BASYX_CORS_ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--output-document=-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - basyx-java-server-sdk
      
  aas-discovery:
    container_name: aas-discovery
    image: eclipsebasyx/aasdiscovery-go:SNAPSHOT
    environment:
      - VIRTUAL_HOST=discovery.basyx.localhost
      - VIRTUAL_PORT=8081
      - SERVER_PORT=8081
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=true
      - ABAC_MODELPATH=/security_env/access-rules.json
      - OIDC_TRUSTLISTPATH=/security_env/trustlist.json
    ports:
      - "8084:8081"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--output-document=-", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
      keycloak-healthcheck:
        condition: service_completed_successfully
    volumes:
      - ./security_env:/security_env
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    networks:
      - basyx-java-server-sdk

  keycloak:
    image: keycloak/keycloak:26.0.6
    container_name: keycloak
    environment:
      VIRTUAL_HOST: keycloak.basyx.localhost
      VIRTUAL_PORT: "8080"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/basyxTestDB
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin123
      KC_HOSTNAME: keycloak.basyx.localhost
      KC_HOSTNAME_PORT: "80"
      KC_HOSTNAME_URL: "http://keycloak.basyx.localhost"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_IMPORT: /opt/keycloak/data/import/
      KC_HTTP_MANAGEMENT_ENABLED: "true"
    command: ["start-dev", "--import-realm", "--health-enabled=true"]
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      - basyx-java-server-sdk

  keycloak-healthcheck:
    image: curlimages/curl:latest
    container_name: keycloak-healthcheck
    command: >
      sh -c "
        echo 'Waiting for Keycloak to become ready...';
        until curl -sf http://keycloak:9000/health/ready; do
          sleep 5;
        done;
        echo 'Keycloak is ready!'"
    depends_on:
      - keycloak
    networks:
      - basyx-java-server-sdk
      
  aas-ui:
    container_name: aas-web-ui
    image: eclipsebasyx/aas-gui:SNAPSHOT
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: aasgui.basyx.localhost
      VIRTUAL_PORT: "3000"
      AAS_REGISTRY_PATH: "http://aasreg.basyx.localhost/shell-descriptors"
      SUBMODEL_REGISTRY_PATH: "http://smreg.basyx.localhost/submodel-descriptors"
      AAS_DISCOVERY_PATH: "http://discovery.basyx.localhost/lookup/shells"
      AAS_REPO_PATH: "http://aasenv.basyx.localhost/shells"
      SUBMODEL_REPO_PATH: "http://aasenv.basyx.localhost/submodels"
      CD_REPO_PATH: "http://aasenv.basyx.localhost/concept-descriptions"
      KEYCLOAK_URL: "http://keycloak.basyx.localhost"
      KEYCLOAK_REALM: basyx
      KEYCLOAK_CLIENT_ID: basyx-web-ui
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    restart: always
    depends_on:
      aas-environment:
        condition: service_started
    networks:
      - basyx-java-server-sdk

  # PostgreSQL database
  db:
    container_name: postgres_db
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxTestDB
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxTestDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - basyx-java-server-sdk

  aas-environment:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: secured-aas-env
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
      - "discovery.basyx.localhost:host-gateway"
      - "smreg.basyx.localhost:host-gateway"
      - "aasreg.basyx.localhost:host-gateway"
    volumes:
      - ./aas:/application/aas
      - ./security_env/aas-env-rules.json:/application/rbac_rules.json
    ports:
      - '8081:8081'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: aasenv.basyx.localhost
      VIRTUAL_PORT: "8081"
      # Component configuration
      SERVER_PORT: 8081
      BASYX_BACKEND: InMemory
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: 'GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD'
      BASYX_ENVIRONMENT: file:aas
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION: http://discovery.basyx.localhost
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aasreg.basyx.localhost
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://smreg.basyx.localhost
      BASYX_EXTERNALURL: http://aasenv.basyx.localhost
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 1024MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 1024MB
      # Security configuration
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: file:/application/rbac_rules.json
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak.basyx.localhost/realms/basyx
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_TOKEN_ENDPOINT: http://keycloak.basyx.localhost/realms/basyx/protocol/openid-connect/token
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_CLIENT_ID: aas-env
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_CLIENT_SECRET: gqj6bXy7uBx0F97mXzy4vOsnD1frqYcB
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_ENABLED: true
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_TOKEN_ENDPOINT: http://keycloak.basyx.localhost/realms/basyx/protocol/openid-connect/token
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_CLIENT_ID: aas-env
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_CLIENT_SECRET: gqj6bXy7uBx0F97mXzy4vOsnD1frqYcB
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_ENABLED: true
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_TOKEN_ENDPOINT: http://keycloak.basyx.localhost/realms/basyx/protocol/openid-connect/token
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_ID: aas-env
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_SECRET: gqj6bXy7uBx0F97mXzy4vOsnD1frqYcB
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_ENABLED: true
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_TOKEN_ENDPOINT: http://keycloak.basyx.localhost/realms/basyx/protocol/openid-connect/token
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_ID: aas-env
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_SECRET: gqj6bXy7uBx0F97mXzy4vOsnD1frqYcB
    depends_on:
      aas-discovery:
        condition: service_healthy
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      keycloak-healthcheck:
        condition: service_completed_successfully
    networks:
      - basyx-java-server-sdk

networks:
  basyx-java-server-sdk:
    name: basyx-java-server-sdk
    driver: bridge
